-- Initialise authors
INSERT INTO authors (name, created_at, updated_at) VALUES 
    ('N.K. Jemisin', NOW(), NOW()),
    ('J.K. Rowling', NOW(), NOW()),
    ('Roald Dahl', NOW(), NOW()),
    ('William Peter Blatty', NOW(), NOW());

-- Initialise books
INSERT INTO books (name, created_at, updated_at) VALUES 
    ('The Stone Sky', NOW(), NOW()),
    ('The Obelisk Gate', NOW(), NOW()),
    ('The Fifth Season', NOW(), NOW()),
    ('The Exorcist', NOW(), NOW()),
    ('Harry Potter 5', NOW(), NOW()),
    ('Harry Potter 6', NOW(), NOW()),
    ('Harry Potter 7', NOW(), NOW()),
    ('Harry Potter 8', NOW(), NOW()),
    ('Harry Potter 9', NOW(), NOW()),
    ('Harry Potter 10', NOW(), NOW()),
    ('Harry Potter 11', NOW(), NOW()),
    ('Harry Potter 12', NOW(), NOW()),
    ('Harry Potter 13', NOW(), NOW()),
    ('Harry Potter 14', NOW(), NOW());

-- Initialise people
INSERT INTO people (name, country_id, created_at, updated_at) VALUES 
    ('Amy2', 702, NOW(), NOW()),
    ('Amy1', 702, NOW(), NOW()),
    ('Amy3', 702, NOW(), NOW()),
    ('Amy4', 702, NOW(), NOW()),
    ('Bob1', 458, NOW(), NOW()),
    ('Amy5', 702, NOW(), NOW()),
    ('Bob2', 458, NOW(), NOW()),
    ('Bob3', 458, NOW(), NOW()),
    ('Bob4', 458, NOW(), NOW()),
    ('Bob5', 458, NOW(), NOW()),
    ('Bob6', 458, NOW(), NOW()),
    ('Bob7', 458, NOW(), NOW()),
    ('Bob8', 458, NOW(), NOW()),
    ('Charles1', 840, NOW(), NOW()),
    ('Charles2', 840, NOW(), NOW()),
    ('Charles3', 840, NOW(), NOW()),
    ('Charles4', 840, NOW(), NOW()),
    ('Charles5', 840, NOW(), NOW()),
    ('Charles6', 840, NOW(), NOW()),
    ('Charles7', 840, NOW(), NOW()),
    ('Charles8', 840, NOW(), NOW()),
    ('Charles9', 840, NOW(), NOW());

-- Initiliase author_books
INSERT INTO author_books (author_id, book_id, created_at, updated_at) VALUES 
    (1, 1, NOW(), NOW()),
    (1, 2, NOW(), NOW()),
    (1, 3, NOW(), NOW()),
    (4, 4, NOW(), NOW()),
    (3, 14, NOW(), NOW()),
    (2, 5, NOW(), NOW()),
    (2, 6, NOW(), NOW()),
    (2, 7, NOW(), NOW()),
    (2, 8, NOW(), NOW()),
    (2, 9, NOW(), NOW()),
    (2, 10, NOW(), NOW()),
    (2, 11, NOW(), NOW()),
    (2, 12, NOW(), NOW()),
    (2, 13, NOW(), NOW());

-- Initialise book_rents
INSERT INTO book_rents (person_id, book_id, created_at, updated_at) VALUES 
    (1, 1, NOW(), NOW()),
    (1, 1, NOW(), NOW()),
    (1, 1, NOW(), NOW()),
    (1, 1, NOW(), NOW()),
    (1, 1, NOW(), NOW()),
    (1, 1, NOW(), NOW()),
    (1, 1, NOW(), NOW()),
    (1, 1, NOW(), NOW()),
    (1, 1, NOW(), NOW()),
    (1, 1, NOW(), NOW()),
    (1, 1, NOW(), NOW()),
    (1, 1, NOW(), NOW()),
    (2, 1, NOW(), NOW()),
    (2, 1, NOW(), NOW()),
    (3, 1, NOW(), NOW()),
    (4, 1, NOW(), NOW()),
    (5, 1, NOW(), NOW()),
    (2, 1, NOW(), NOW()),
    (3, 1, NOW(), NOW()),
    (4, 1, NOW(), NOW()),
    (6, 1, NOW(), NOW()),
    (1, 2, NOW(), NOW()),
    (1, 2, NOW(), NOW()),
    (1, 2, NOW(), NOW()),
    (2, 2, NOW(), NOW()),
    (2, 2, NOW(), NOW()),
    (2, 2, NOW(), NOW()),
    (2, 2, NOW(), NOW()),
    (2, 2, NOW(), NOW()),
    (2, 2, NOW(), NOW()),
    (2, 2, NOW(), NOW()),
    (2, 2, NOW(), NOW()),
    (2, 2, NOW(), NOW()),
    (2, 2, NOW(), NOW()),
    (2, 2, NOW(), NOW()),
    (2, 2, NOW(), NOW()),
    (2, 2, NOW(), NOW()),
    (1, 2, NOW(), NOW()),
    (3, 3, NOW(), NOW()),
    (3, 3, NOW(), NOW()),
    (3, 3, NOW(), NOW()),
    (3, 3, NOW(), NOW()),
    (3, 3, NOW(), NOW()),
    (4, 5, NOW(), NOW()),
    (4, 5, NOW(), NOW()),
    (4, 5, NOW(), NOW()),
    (4, 5, NOW(), NOW()),
    (4, 5, NOW(), NOW()),
    (4, 5, NOW(), NOW()),
    (4, 5, NOW(), NOW()),
    (4, 5, NOW(), NOW()),
    (16, 5, NOW(), NOW()),
    (14, 5, NOW(), NOW()),
    (6, 8, NOW(), NOW()),
    (14, 8, NOW(), NOW()),
    (14, 8, NOW(), NOW()),
    (14, 8, NOW(), NOW());
